name: Hello World Workflow

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  say-hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Say hello
        run: echo "Hello world!"
